# Generated by Django 2.2 on 2021-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=64, null=True)),
                ('source', models.CharField(db_index=True, max_length=64, null=True)),
                ('product_type', models.CharField(db_index=True, max_length=64, null=True)),
                ('product_name', models.CharField(db_index=True, max_length=64, null=True)),
                ('calss_course', models.CharField(db_index=True, max_length=64, null=True)),
                ('difficulty_level', models.CharField(db_index=True, max_length=64, null=True)),
                ('content_direction', models.CharField(db_index=True, max_length=64, null=True)),
                ('class_size', models.CharField(db_index=True, max_length=64, null=True)),
                ('teaching_assistant', models.CharField(db_index=True, max_length=64, null=True)),
                ('sales', models.CharField(db_index=True, max_length=64, null=True)),
                ('teacher', models.CharField(db_index=True, max_length=64, null=True)),
                ('date_of_purchasing', models.CharField(db_index=True, max_length=64, null=True)),
                ('product', models.CharField(db_index=True, max_length=64, null=True)),
                ('date_of_lecture', models.CharField(db_index=True, max_length=64, null=True)),
                ('hours_of_lecture', models.CharField(db_index=True, max_length=64, null=True)),
                ('has_been_lecture', models.CharField(db_index=True, max_length=64, null=True)),
                ('the_remaining_lecture', models.CharField(db_index=True, max_length=64, null=True)),
                ('price_per_hour', models.CharField(db_index=True, max_length=64, null=True)),
                ('price_overall', models.CharField(db_index=True, max_length=64, null=True)),
                ('cur_state', models.CharField(db_index=True, max_length=64, null=True)),
                ('follow_period', models.CharField(db_index=True, max_length=64, null=True)),
                ('follow_number', models.CharField(db_index=True, max_length=64, null=True)),
                ('warning_show', models.CharField(db_index=True, default='true', max_length=64)),
            ],
        ),
    ]
