# Generated by Django 2.2 on 2021-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_state', models.CharField(db_index=True, max_length=500, null=True)),
                ('source', models.CharField(db_index=True, max_length=64, null=True)),
                ('date_to_add', models.CharField(db_index=True, max_length=64, null=True)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('transfer_time', models.CharField(db_index=True, max_length=64, null=True)),
                ('signing_time', models.CharField(db_index=True, max_length=64, null=True)),
                ('gender', models.CharField(db_index=True, max_length=20, null=True)),
                ('wechat_num', models.CharField(db_index=True, max_length=64, null=True)),
                ('area', models.CharField(db_index=True, max_length=64, null=True)),
                ('phone', models.CharField(db_index=True, max_length=64, null=True)),
                ('little_assistant', models.CharField(db_index=True, max_length=64, null=True)),
                ('consultant', models.CharField(db_index=True, max_length=64, null=True)),
                ('service_consultant', models.CharField(db_index=True, max_length=64, null=True)),
                ('paper_writer', models.CharField(db_index=True, max_length=64, null=True)),
                ('strategy_consultant', models.CharField(db_index=True, max_length=64, null=True)),
                ('identity', models.CharField(max_length=64, null=True)),
                ('school_type', models.CharField(db_index=True, max_length=64, null=True)),
                ('school', models.CharField(db_index=True, max_length=64, null=True)),
                ('curriculum_system', models.CharField(db_index=True, max_length=64, null=True)),
                ('curriculum_system_note', models.CharField(db_index=True, max_length=64, null=True)),
                ('graduation_date', models.CharField(max_length=64, null=True)),
                ('application_level', models.CharField(db_index=True, max_length=64, null=True)),
                ('major', models.CharField(max_length=64, null=True)),
                ('target_country', models.CharField(max_length=64, null=True)),
                ('TOEFL', models.CharField(default='', max_length=64)),
                ('IELTS', models.CharField(default='', max_length=64)),
                ('SAT', models.CharField(default='', max_length=64)),
                ('ACT', models.CharField(default='', max_length=64)),
                ('GRE', models.CharField(default='', max_length=64)),
                ('customer_remarks', models.CharField(default='', max_length=64)),
                ('warning_show', models.CharField(db_index=True, default='false', max_length=64)),
                ('transfer_to_beenlost', models.CharField(default='', max_length=64, null=True)),
            ],
        ),
    ]
